version: "3.7"

services:
   bind9:
     
     image: ubuntu/bind9
     container_name: bind9
     environment: 
        - TZ=UTC
     ports:
        - 53:53 

     volumes:
       - ./named.conf:/etc/bind/named.conf
       - ./bind:/var/cache/bind
       - ./bind:/var/lib/bind
    
